FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# loan-application API

Loan application is a simple API allowing consumers to subscribe a loan.

![alt text](https://github.com/willy77/loan-api/blob/master/model.jpg?raw=true)

To create a Loan follow the following process:

 1. [Create a loan request](#create_loan_request)
 2. [Ask for simulation](#create_loan_simulation)
 3. [Retreive simulation result](#read_simulation_result).

In the document, the following convention apply:

 - All amounts are in cts.
 - All rates are multiplied by 10000

Each request allows you to add the following headers:
- The `X-transactionId` header allows you to send your transaction id, in order to help us when debuging.


## Loan request [/loan_requests/{request_id}]

### Retrieve the loan object [GET]

Retreive a loan request


+ Parameters
    + request_id (string, required) - ID of the loan request
+ Response 200 (application/json)
   When  found
    + Headers
    
            X-transactionId: 123456789
            X-test-mode: true
        
    + Attributes (LoanRequest)

+ Response 404 (application/json)
    Not  found
    + Headers
    
            X-transactionId: 123456789
            X-test-mode: true

## Loan requests Collection [/loan_requests]
<a id="create_loan_request"></a>
### create a new loan request [POST]

Creates a loan request

- The `X-test-mode` header allow us to run the loan application in test mode, and the resulting proposal will not be taken in account.

+ Request
    + Headers
    
            X-transactionId: 123456789
            X-test-mode: true
            
    + Attributes (LoanRequest)
    
+ Response 201 (application/json)
    + Headers

            X-transactionId: 123456789
            X-test-mode: true
            Location: loan_requests/{request_id}

## Loan request Simulation Collection [/loan_requests/{request_id}/simulations]

<a id="create_loan_simulation"></a>
### Create a new loan request simulations [POST]

Creates a loan request simulation

+ Parameters
    + request_id (string, required) - ID of the loan request

+ Request
    + Headers
    
            X-transactionId: 123456789

    + Attributes (CustomisationContext)
    
+ Response 201 (application/json)
    + Headers

            X-transactionId: 123456789
            X-test-mode: true
            Location: loan_requests/{request_id}/simulations

### Retreive simulations result [GET]
<a id="read_simulation_result"></a>

+ Parameters
    + request_id (string, required) - ID of the loan request

+ Request
    + Headers
    
            X-transactionId: 123456789

+ Response 200 (application/json)
    + Headers

            X-transactionId: 123456789
            X-test-mode: true

    + Attributes (array[SimulationGroup])


## Data Structures

### LoanRequest
+ vendorId: 1001989870P (string, required)
   Your vendor identifier.
+ project (Project,required)

### Project

+ personal_financing (PersonnalFinancing, required)

### PersonnalFinancing
+ category: 50,251,252 (enum,required)
    the material code
+ amount (Amount,required)
    The amount in cts.
+ term: 20 (number, required)
    The loan term in month.
+ read_only: false (boolean, optional)
    Indicates if the loan object can be modifed.
    
### CustomisationContext

+ product_family: CLASSICAL, REVOLVING (enum, optional)
+ engagement: NONE, SCORED, FINAL (enum,optional)

### SimulationGroup

+ rank: 10 (number)
+ kind: result, sample (enum)
+ simulations (array[Simulation])

### Simulation

+ id: 01
+ type: main,secondary,alternative (enum)
  When several simulation are present in a group, they can play different roles.
+ rating: LOW,HIGH,FIXED (enum,optional)
+ proposal (enum)
    + (ClassicalFinancing)
    + (RevolvingFinancing)

### AbstractLoanProposal
+ term: 20 (number, required)
+ requested_amount  (Amount,required)
+ rate (RATE)
+ TAEG (RATE)
+ insurance_included: false (boolean)
+ total_amount (Amount, required)
+ interest  (Amount)
+ insurance (Insurance)
+ loan_cost (Amount,required)

### ClassicalFinancing (AbstractLoanProposal)
+ monthly_payment (Amount,required)
+ fees (Amount)

### RevolvingFinancing (AbstractLoanProposal)
+ maxterm: 24 (number, required)
+ installments (array[Installment],required)


### RATE
+ kind: fixed,variable (enum,required)
+ value: 26900 (number, required)

### Insurance

+ rating: LOW,HIGH,FIXED (enum,optional)
+ amount (Amount)
+ total_amount (Amount)
+ TAEA (RATE)

### Installment
+ number: 19 (number, required)
+ amount (Amount, required)

### Amount
+ value: 1000 (number,required)
+ currency: EUR,GBP (enum)